CREATE TABLE t_import_pcp_van_tmp (
  tmp_id          int(11) NOT NULL AUTO_INCREMENT,
  vanid           varchar(14) DEFAULT NULL,
  vanprecinct     varchar(40) DEFAULT NULL,
  mcedprecinct    int(11) DEFAULT NULL,
  lname           varchar(40) DEFAULT NULL,
  fname           varchar(40) DEFAULT NULL,
  middlename      varchar(40) DEFAULT NULL,
  nickname        varchar(40) DEFAULT NULL,
  suffix          varchar(10) DEFAULT NULL,
  gender          varchar(10) DEFAULT NULL,
  r_address       varchar(100) DEFAULT NULL,
  r_city          varchar(40) DEFAULT NULL,
  r_state         char(2) DEFAULT 'OR',
  r_zip           varchar(15) DEFAULT NULL,
  r_zip4          varchar(15) DEFAULT NULL,
  r_country_code  char(2) DEFAULT 'US',
  email           varchar(100) DEFAULT NULL,
  phone           varchar(20) DEFAULT NULL,
  phone2          varchar(20) DEFAULT NULL,
  m_address       varchar(100) DEFAULT NULL,
  m_city          varchar(40) DEFAULT NULL,
  m_state         char(2) DEFAULT 'OR',
  m_zip           varchar(15) DEFAULT NULL,
  m_zip4          varchar(15) DEFAULT NULL,
  assignment      varchar(40) DEFAULT NULL,
  cd              int(11) DEFAULT NULL,
  PRIMARY KEY (tmp_id),
  UNIQUE KEY precinct_UNIQUE (tmp_id)
) ;