CREATE TABLE t_imp_mced_xl (
  tmp_id            int(11) NOT NULL AUTO_INCREMENT,
  person_id         int(11) ,
  precinct          int(11) DEFAULT NULL,
  position          VARCHAR(40) DEFAULT 'Precinct Committee Person - Democrat',
  voter_id          varchar(14) DEFAULT NULL,
  fname             varchar(40) DEFAULT NULL,
  middlename        varchar(40) DEFAULT NULL,
  lname             varchar(40) DEFAULT NULL,
  suffix            varchar(10) DEFAULT NULL,
  m_address         varchar(100) DEFAULT NULL,
  m_city            varchar(40) DEFAULT NULL,
  m_state           char(2) DEFAULT NULL,
  m_zip             varchar(15) DEFAULT NULL,
  party             varchar(15) DEFAULT 'Democrat',
  r_address         varchar(100) DEFAULT NULL,
  r_city            varchar(40) DEFAULT NULL,
  r_state           char(2) DEFAULT NULL,
  r_zip             varchar(15) DEFAULT NULL,
  status            varchar(20) DEFAULT NULL,
  start_date_str    varchar(20) DEFAULT NULL,
  end_date_str      VARCHAR(20) DEFAULT NULL,
  start_date        varchar(20) DEFAULT NULL,
  end_date          varchar(20) DEFAULT NULL,
  skey_long         VARCHAR(120) DEFAULT NULL,
  skey_short        VARCHAR(120) DEFAULT NULL,
  PRIMARY KEY       primary_key (tmp_id),
  UNIQUE KEY        pk_unique_idx (tmp_id),
  KEY               person_idx (person_id), 
  KEY               skey_l_idx(skey_long),
  KEY               skey_s_idx(skey_short)
);
